### ISSUE TITLE
Autocomplete not working

### ISSUE THREAD

**Issue by freshface** [Logicify/jquery-locationpicker-plugin#73] opened 2016-06-24 10:13 UTC
I am loading the google api with the key:

`<script type="text/javascript" src='https://maps.googleapis.com/maps/api/js?key=MYKEY0&libraries=places'></script>
`

But the autocomplete isnt working anymore, any suggestion (and yes, the enableAutocomplete: true is enabled)

**Comment by sayeed958** [comment] 2016-06-24 11:06
Yes I am also facing same issue, Its working on local machine but while transferred code on live server and accessing through main domain auto complete is not working.

**Comment by freshface** [comment] 2016-06-24 11:14
I am working locally, not live.

**Comment by waqasraza123** [comment] 2016-06-28 19:35
autocomplete is not working here too.

**Comment by timbkbasic** [comment] 2016-07-05 21:51
For me, the fix was that I had to go to the Google Developer Console and enable "Google Places API Web Service". Once I enabled this API, the autocomplete started working again.

**Comment by nealoke** [comment] 2016-07-10 11:48
@timbkbasic is totally right! Go to https://developers.google.com/places/web-service/ and just make an API key for this one (no need to include it anywhere in your requests or script tag. Once added the autocomplete works!

**Comment by FewKinG** [comment] 2016-08-11 19:05
It should be noted though, that this will result in your autocomplete requests being limited on a per-api-project basis and not per user. So when you have a lot of users, you will quickly reach the quota there and your app will start failing... I'm wondering how that seemed to go unnoticed so far for so many users of this API.

**Comment by nealoke** [comment] 2016-08-12 12:01
@FewKinG are you reffering to the solution by @timbkbasic or the plugin itself?

**Comment by FewKinG** [comment] 2016-08-15 07:14
@nealoke I was referring to @timbkbasic 's solution. Enabling "Google Places API Web Service" helped fix the issue but resulted in the API calls being counted towards the Web Service quota which is not counted per user but per project.

**Comment by nealoke** [comment] 2016-08-15 11:53
@FewKinG aah that's no good :/ Any workarounds?

**Comment by FewKinG** [comment] 2016-08-15 12:06
Not yet, don't know if there is any. Google's official documentation states that you should be able to use the Places library in the Maps SDK for client-side places autocompletion (by adding libraries=places to the script tag src). And that should then be counted per user. The Places API Web Service should only be used for server-to-server queries. Therefore I'd consider the actual behavior to go against the documentation.

**Comment by nealoke** [comment] 2016-08-15 12:33
@FewKinG have you tried this again? I am pretty sure I've tried this as well but can't really remember... If it doesn't work it means that it is a bug on their side no?

**Comment by T3RON** [comment] 2016-09-07 11:23
autocomplete is not working on live server

**Comment by Sumragen** [comment] 2016-09-12 13:02
It issue is same like #85. 
[Try it](https://github.com/Logicify/jquery-locationpicker-plugin/issues/85#issuecomment-246318493). I think it must help you.

**Comment by Sumragen** [comment] 2016-09-16 12:33
Also, look at [this ticket](https://github.com/Logicify/jquery-locationpicker-plugin/issues/32).

**Closed** 2016-09-20 14:11 UTC

**Comment by FewKinG** [comment] 2016-10-13 11:11
Hey, quick update from my side, the need to enable and use the Places API Web Service which I mentioned earlier, is (now, finally) documented and expected behavior at Google. See this, point 4:

https://developers.google.com/maps/pricing-and-plans/standard-plan-2016-update

Not the greatest news, because it tightens the boundaries on what you can do for free, but at least it's official now.

**Comment by nehaanand** [comment] 2019-04-02 11:01
I have enabled credit card billing also but still PlaceAutoComplete code not working in Android.It says Places Api access not configured.

**Comment by timbkbasic** [comment] 2019-04-02 14:55
Even after you enable billing, you still need to go to the API configuration to enable individual APIs.
